[package]
name = "orion-discord-bot"
version = "0.1.0"
authors = ["TURCHINI GUILLAUME <orion78fr@gmail.com>"]
edition = "2018"

[dependencies.discord]
git = "https://github.com/SpaceManiac/discord-rs"
default-features = false