[package]
name = "orion-discord-bot"
version = "0.1.0"
authors = ["TURCHINI GUILLAUME <orion78fr@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1"
pest_derive = "2.1"

[dependencies.serenity]
version = "0.5"